-- Supabase Database Schema
-- Run this in your Supabase project's SQL Editor to set up the necessary tables and Row Level Security (RLS) policies.

-- 1. Create the projects table
CREATE TABLE IF NOT EXISTS projects (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL,
  description TEXT,
  image TEXT,
  tech_stack TEXT[] DEFAULT '{}'::TEXT[],
  html_url TEXT,
  stargazers_count INTEGER DEFAULT 0,
  forks_count INTEGER DEFAULT 0,
  updated_at TIMESTAMPTZ DEFAULT NOW(),
  featured BOOLEAN DEFAULT FALSE
);

-- 2. Create the tech_stack table
CREATE TABLE IF NOT EXISTS tech_stack (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL,
  category TEXT NOT NULL,
  icon TEXT -- Holds the SVG markup string
);

-- 3. Enable Row Level Security (RLS) on both tables
ALTER TABLE projects ENABLE ROW LEVEL SECURITY;
ALTER TABLE tech_stack ENABLE ROW LEVEL SECURITY;

-- 4. Set RLS Policies for projects
-- Public SELECT policy
CREATE POLICY "Allow public read-only access on projects"
  ON projects FOR SELECT
  USING (true);

-- Authenticated INSERT policy
CREATE POLICY "Allow authenticated insert on projects"
  ON projects FOR INSERT
  TO authenticated
  WITH CHECK (true);

-- Authenticated UPDATE policy
CREATE POLICY "Allow authenticated update on projects"
  ON projects FOR UPDATE
  TO authenticated
  USING (true)
  WITH CHECK (true);

-- Authenticated DELETE policy
CREATE POLICY "Allow authenticated delete on projects"
  ON projects FOR DELETE
  TO authenticated
  USING (true);

-- 5. Set RLS Policies for tech_stack
-- Public SELECT policy
CREATE POLICY "Allow public read-only access on tech_stack"
  ON tech_stack FOR SELECT
  USING (true);

-- Authenticated INSERT policy
CREATE POLICY "Allow authenticated insert on tech_stack"
  ON tech_stack FOR INSERT
  TO authenticated
  WITH CHECK (true);

-- Authenticated UPDATE policy
CREATE POLICY "Allow authenticated update on tech_stack"
  ON tech_stack FOR UPDATE
  TO authenticated
  USING (true)
  WITH CHECK (true);

-- Authenticated DELETE policy
CREATE POLICY "Allow authenticated delete on tech_stack"
  ON tech_stack FOR DELETE
  TO authenticated
  USING (true);

-- 6. Create the experience table
CREATE TABLE IF NOT EXISTS experience (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  company TEXT NOT NULL,
  role TEXT NOT NULL,
  duration TEXT NOT NULL,
  description TEXT
);

-- 7. Enable RLS on experience table
ALTER TABLE experience ENABLE ROW LEVEL SECURITY;

-- 8. Set RLS Policies for experience
-- Public SELECT policy
CREATE POLICY "Allow public read-only access on experience"
  ON experience FOR SELECT
  USING (true);

-- Authenticated INSERT policy
CREATE POLICY "Allow authenticated insert on experience"
  ON experience FOR INSERT
  TO authenticated
  WITH CHECK (true);

-- Authenticated UPDATE policy
CREATE POLICY "Allow authenticated update on experience"
  ON experience FOR UPDATE
  TO authenticated
  USING (true)
  WITH CHECK (true);

-- Authenticated DELETE policy
CREATE POLICY "Allow authenticated delete on experience"
  ON experience FOR DELETE
  TO authenticated
  USING (true);

